### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by marcokim1** [Airstack-xyz/farcaster-moxie-exclusion-list#12]
fid : 508575

![Screenshot_20240905_210437_Chrome](https://github.com/user-attachments/assets/017bc419-0ab7-44b8-b580-292b20c48066)

I am not a bot, and I believe my account has been mistakenly flagged. I request that my account be unflagged as soon as possible. I follow all platform rules and guidelines, and I would appreciate it if you could review my account activity to resolve this issue. Thank you for your attention to this matter.

**Comment by shnoodles** [comment]
it's not flagged by the system
