### ISSUE TITLE
New issues

### ISSUE THREAD

**Issue by jinsungting** [Airstack-xyz/farcaster-moxie-exclusion-list#15]
My pid : 425967
Moxie protocol TVL : 260,903KMOXIE (My TVL : 320.763K MOXIE)

![IMG_8788](https://github.com/user-attachments/assets/1c9b75e4-46f5-4584-ba01-879e5cbfc7c3)

reason : I'm not a bot. I'm asking to unlock my account because it seems to be locked incorrectly. I promise to follow all the rules on the platform, and I want a chance to continue using this account. Please review it and resolve it quickly. Thank you.

**Comment by shnoodles** [comment]
unflagged
