### ISSUE TITLE
New issues

### ISSUE THREAD

**Issue by marcokim1** [Airstack-xyz/farcaster-moxie-exclusion-list#16]
fid : 508575

![Screenshot_20240906_194809_Chrome](https://github.com/user-attachments/assets/c157dfa3-f203-4a7e-b603-58b74846df03)

I am not a bot. I believe my account has been mistakenly locked, and I request that it be unlocked. I adhere to all the platform's rules and guidelines and would like the opportunity to continue using my account. Please review my account activity and help resolve this issue as soon as possible. Thank you for your assistance. 🙏

**Comment by shnoodles** [comment]
You are not in the list:
https://github.com/Airstack-xyz/farcaster-moxie-exclusion-list/blob/main/farcaster_moxie_exclusion.json
