### ISSUE TITLE
Fid 307726 

### ISSUE THREAD

**Issue by herlengs** [Airstack-xyz/farcaster-moxie-exclusion-list#17]
Fid 307726
Moxie Protocol TVL : 30,247 MOXIE 
I'm definitely not a bot. 
I'll be more careful about communicating through comments.
Please review it again. Help me 
![스크린샷 2024-09-07 000750](https://github.com/user-attachments/assets/27601cb3-dd22-4d9a-9031-6a7d62a6d1ed)

**Comment by shnoodles** [comment]
unflagged
