### ISSUE TITLE
FID: 636798

### ISSUE THREAD

**Issue by Basedkitty** [Airstack-xyz/farcaster-moxie-exclusion-list#18]
FID: 636798
TVL (240.95k)
![IMG_0970](https://github.com/user-attachments/assets/829b0033-c9ca-46ec-82ea-ed8559556b20)

i’m not a bot as you can see bot dont  Dm and ask for help i did not know about the flagged system and i think i made a mistake by engaging more in hour with my followers
I’ll be carefull for next time for sure i think everyone deserve second chance so i am 
I appreciate your concerned about bots and spamming

**Comment by shnoodles** [comment]
unflagged
