### ISSUE TITLE
PR/Raise an issue

### ISSUE THREAD

**Issue by december98ace** [Airstack-xyz/farcaster-moxie-exclusion-list#21]
Account FID: 492032

Moxie Protocol TVL: 166.723 MOXIE
![화면 캡처 2024-09-07 115719](https://github.com/user-attachments/assets/3a4a95e2-9486-433e-b3e9-cdddcf21f737)

In the process of writing replies to friends' casts, it seems that they exceeded the limit of 100 replies allowed per hour. If you check the content and time interval of the replies I wrote, you can confirm that I did not use the bot. I will be more careful in the future.

**Comment by shnoodles** [comment]
unflagged
