### ISSUE TITLE
moxie jail issues

### ISSUE THREAD

**Issue by cocoduckchun** [Airstack-xyz/farcaster-moxie-exclusion-list#23]
FID 512874

![noname](https://github.com/user-attachments/assets/c0427cad-0c8f-4c64-b3ba-daad267904bd)

I explained on August 24th that I'm not a bot on DM and got a reply saying "let me free from jail" but I'm in jail so far.

I was told I shouldn't post more than 100 replies an hour, so I did, but I couldn't get out of jail. Please check 
tysm

**Comment by shnoodles** [comment]
Your account is not in jail
