### ISSUE TITLE
PR/Raise Issue of Jail

### ISSUE THREAD

**Issue by ramuka777** [Airstack-xyz/farcaster-moxie-exclusion-list#24]
Account FID: 478311

Moxie Protocol TVL: 273.789K MOXIE
![image](https://github.com/user-attachments/assets/9d8af119-023f-4855-9476-c8eccd928056)

I am absolutely not a bot, but rather a user who loves Moxie. While replying to a friend's cast, I think I may have exceeded the 100 replies per hour limit. I have never used copy-paste and have always engaged in genuine conversations. I understand that the "jail check" frame is currently displayed, and I will be more mindful while communicating with my friends moving forward. I will continue to contribute to the development of Moxie.
BTW, The "jail check" frame shows "FREE," but I am unable to claim it. Does this mean I am still in jail?

**Comment by shnoodles** [comment]
unflagged
