### ISSUE TITLE
pr/issue

### ISSUE THREAD

**Issue by hj222a** [Airstack-xyz/farcaster-moxie-exclusion-list#26]
1.My pid : 488767
2.Moxie protocol TVL : 372,595,013 MOXIE (My TVL : 104.664K MOXIE)
3.reason : 
I have a Moxy Prison frame, so I didn't even make 30 interactions an hour while watching this. We need an explanation as to why we are going to jail.

**Comment by shnoodles** [comment]
account is not flagged
