### ISSUE TITLE
moxie jail issue

### ISSUE THREAD

**Issue by zzulove12** [Airstack-xyz/farcaster-moxie-exclusion-list#28]
1. Account FID : 508096
2.
![111](https://github.com/user-attachments/assets/f323a762-48e4-469e-828a-7bab732552ea)

3. I'm not a bot. I'm asking to unlock my account because it seems to be locked incorrectly. I promise to follow all the rules on the platform, and I want a chance to continue using this account. Please review it and resolve it quickly. Thank you.

**Comment by shnoodles** [comment]
unflagged
