### ISSUE TITLE
moxie jail

### ISSUE THREAD

**Issue by senajoo** [Airstack-xyz/farcaster-moxie-exclusion-list#31]
FID : 350698

![스크린샷 2024-09-09 오후 11 47 44](https://github.com/user-attachments/assets/9b3dc4e8-e203-4ad9-ae06-4a8b1c0443a5)

Maybe I got flagged due to exceeding the number of replies. I'm not a bot that can be on the computer all day. I just wanted to stop by and say hi to my friends whenever I had a little free time.
Please, I beg you, let me out of jail. I just wanted to enjoy conversations with my friends.

**Comment by shnoodles** [comment]
Unflagged for now.
