### ISSUE TITLE
Moxie jail issue

### ISSUE THREAD

**Issue by pirameti** [Airstack-xyz/farcaster-moxie-exclusion-list#33]
I feel like I'm in prison, so I'm sending you a DM. I've never interacted like this on SNS, so I was having so much fun that I left so many comments. I'm sorry. I will use it in accordance with the rules.
I have many fan token, but I bidding new fan token . Plz let me free , sorry

My fid : 480682
![Screenshot_20240910_014021_Chrome](https://github.com/user-attachments/assets/456c6983-66cb-45a3-a835-b0237830b999)
![Screenshot_20240910_014025_Chrome](https://github.com/user-attachments/assets/ad8d820c-ca34-434d-bc03-f07ba4ee0bf5)
![Screenshot_20240910_014036_Chrome](https://github.com/user-attachments/assets/46668cf0-cf21-46b5-b801-f259495cd14f)

**Comment by pirameti** [comment]
Fid is 480682 I'm normal really 
![Uploading Screenshot_20240910_014528_Warpcast.jpg…]()

**Comment by shnoodles** [comment]
duplicate
