### ISSUE TITLE
Moxie jail

### ISSUE THREAD

**Issue by pirameti** [Airstack-xyz/farcaster-moxie-exclusion-list#52]
Account FID: 480682

Moxie Protocol TVL: 33000 MOXIE (can be found on Airstack's website, preferably a screenshot)

Comment why the account should be unflagged

I think this happened because I kept leaving comments on certain posts because I was excited to talk to my friends after a long time. I will follow the rules and be active. I am not a farmer.
![Uploading Screenshot_20240911_073925_Chrome.jpg…]()

**Comment by zygoteenjoy** [comment]
I live in Korea

I'm working at a company.

I'm having fun when I communicate with you

I think he sent you to jail after judging you're a bot

Let me go because I'm communicating with myself

Have a nice day

**Comment by zygoteenjoy** [comment]
Account FID: 508532

I think this happened because I kept leaving comments on certain posts because I was excited to talk to my friends after a long time. I will follow the rules and be active. I am not a farmer.
I'd appreciate it if you could help me

Let me have fun with my friends!
