### ISSUE TITLE
Moxie jail

### ISSUE THREAD

**Issue by sonyong0702** [Airstack-xyz/farcaster-moxie-exclusion-list#53]
1. fid : 496925
2.  
![image](https://github.com/user-attachments/assets/388a898a-0ebc-4fb2-805c-17bff32bc481)

3. I think this happened because I kept leaving comments on certain posts because I was excited to talk to my friends after a long time. I will follow the rules and be active. I am not a farmer.

**Comment by zygoteenjoy** [comment]
moxie jail

I'm not a bot!!!

I'm doing it at the company from time to time

I live in Korea!!!

Let me out of prison!!
