### ISSUE TITLE
Account Flag 

### ISSUE THREAD

**Issue by liai009** [Airstack-xyz/farcaster-moxie-exclusion-list#54]
Fid: 486435
![Screenshot_2024-09-11-17-52-23-552_com android chrome](https://github.com/user-attachments/assets/f9a49018-bff8-4014-a393-b4043e2fefc2)
Hey there! I hope you're having a great day. I believe my account may have been mistakenly flagged and I would really appreciate it if you could take a look and give me another chance. I'm eager to learn more about your community guidelines so I can make sure to follow them in the future. Thank you for your understanding!

**Comment by shnoodles** [comment]
you were manually tagged for farming.
