### ISSUE TITLE
PR/moxie jail

### ISSUE THREAD

**Issue by kamadin10** [Airstack-xyz/farcaster-moxie-exclusion-list#6]
1. Account FID: 412582
2. Moxie protocol TVL: 32,091 MOXIE
3. The should be unflagged because the person didn’t realize that he hadn’t claimed moxie for more than two days leading him to moxie jail. From now on he will follow the rules. Thanks

**Comment by shnoodles** [comment]
FID: 412582 is not in the [list](https://github.com/Airstack-xyz/farcaster-moxie-exclusion-list/blob/main/farcaster_moxie_exclusion.json)
